[package]
name = "box-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.3.1"
http-body-util = "0.1.3"
hyper = {version="1.6.0" ,  features=["full"]}
hyper-util = {version =  "0.1.11" , features= ["full"]}
tokio = {version="1.44.2",   features=["full"]}
